In [63]:
from hmmlearn import hmm
import numpy as np

In [64]:
model = hmm.MultinomialHMM(n_components=2, init_params='')
model.startprob_ = [.8, .2]
model.transmat_ = [[.6, .4], [.5, .5]]
model.emissionprob_ = [[.2, .4, .4], [.5, .4, .1]]

In [65]:
# trước khi fit
o = [3, 1, 3]
o = [[i - 1] for i in o]
print('Likelihood: ', np.exp(model.score(o)))
print('Hidden state best fit: ', model.decode(o))

Likelihood:  0.028562000000000004
Hidden state best fit:  (-4.358310108056566, array([0, 1, 0]))


[0, 1, 0] -> [hot, cold, hot]

In [66]:
O = np.random.binomial(2, 1/3, size=(1000, 3))
model.fit(O)
O

array([[0, 0, 0],
       [0, 0, 1],
       [1, 1, 2],
       ...,
       [1, 1, 1],
       [1, 0, 0],
       [2, 0, 0]])

[1, 1, 0] -> [cold, cold, hot]

In [67]:
# sau khi fit
o = [3, 1, 3]
o = [[i - 1] for i in o]
print('Likelihood: ', np.exp(model.score(o)))
print('Hidden state best fit: ', model.decode(o))

Likelihood:  0.00189545616180856
Hidden state best fit:  (-6.879853105959844, array([1, 1, 0]))


In [ ]:
[cold, cold, hot]

In [49]:
model.startprob_

array([2.81650461e-13, 1.00000000e+00])

In [50]:
model.transmat_

array([[0.56071341, 0.43928659],
       [0.8672801 , 0.1327199 ]])

In [51]:
model.emissionprob_

array([[2.30436282e-01, 6.67192654e-01, 1.02371064e-01],
       [9.99476845e-01, 1.34615918e-05, 5.09693907e-04]])

In [12]:
help(model.score)

Help on method score in module hmmlearn.base:

score(X, lengths=None) method of hmmlearn.hmm.MultinomialHMM instance
    Compute the log probability under the model.
    
    Parameters
    ----------
    X : array-like, shape (n_samples, 1)
        Feature matrix of individual samples.
    lengths : array-like of integers, shape (n_sequences, ), optional
        Lengths of the individual sequences in ``X``. The sum of
        these should be ``n_samples``.
    
    Returns
    -------
    logprob : float
        Log likelihood of ``X``.
    
    See Also
    --------
    score_samples : Compute the log probability under the model and
        posteriors.
    decode : Find most likely state sequence corresponding to ``X``.
    
    Notes
    -----
    Unlike other HMM classes, `MultinomialHMM` ``X`` arrays have shape
    ``(n_samples, 1)`` (instead of ``(n_samples, n_features)``).  Consider using
    `sklearn.preprocessing.LabelEncoder` to transform your input to the right
    format.

